# Generated by Django 5.2.17 on 2026-08-17 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("face_recognition", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FaceEnrollment",
        ),
    ]
